<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitdeee18f8e687fbb084e6215e88f0e781
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PrestaShop\\Module\\blockvaleur\\' => 30,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PrestaShop\\Module\\blockvaleur\\' => 
        array (
            0 => __DIR__ . '/../..' . '/controllers',
        ),
    );

    public static $classMap = array (
        'BlockvaleurActivity' => __DIR__ . '/../..' . '/classes/BlockvaleurActivity.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'blockvaleur' => __DIR__ . '/../..' . '/blockvaleur.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitdeee18f8e687fbb084e6215e88f0e781::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitdeee18f8e687fbb084e6215e88f0e781::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitdeee18f8e687fbb084e6215e88f0e781::$classMap;

        }, null, ClassLoader::class);
    }
}
