<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'BlockvaleurActivity' => $baseDir . '/classes/BlockvaleurActivity.php',
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'blockvaleur' => $baseDir . '/blockvaleur.php',
);
